### PR TITLE
Add testing with GitHub Actions

### PR DESCRIPTION
**Pull request by telemachus**

### CODE REVIEW

**Comment by telemachus** [comment]
So, good news: no hackery needed for the Windows test failures. It turns out that git was the cause. When git checks out files on Windows, it defaults to changing line endings (!). You can override that default with a `.gitattributes` file, and that's what I did here. (See, https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings for more discussion.) That may have one negative side-effect, but I think it's relatively minor. From that same page:

> When you set the `core.autocrlf` option or commit a `.gitattributes` file, you may find that Git reports changes to files that you have not modified. Git has changed line endings to match your new configuration.

I think that would only happen to people who have already downloaded the source on Windows. If it comes up, the fix [is described on that same page](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings).

I set up the tests to run on 1.16, 1.17, and 1.18. You may not want all three, but that's easy to change.

Let me know if there's anything else you'd like me to change. You can see the test runs and logs [in my branch](https://github.com/telemachus/golines/actions) if you want.

**Comment by yolken** [comment]
Nice, LGTM!

**Comment by yolken** [comment]
Also, thanks for digging into the Windows newline issue. I've never done any development on Windows, so I have no idea how things work on that side of the world or how I would go about diagnosing this problem.

**Comment by telemachus** [comment]
> Also, thanks for digging into the Windows newline issue. I've never done any development on Windows, so I have no idea how things work on that side of the world or how I would go about diagnosing this problem.

You're very welcome. I also don't work at all with Windows, and I ended up learning more about git from this problem. If you're ever curious (or need something to put you to sleep), I [wrote a short blog post about it all](https://telemachus.me/git-can-break-your-tests) to help me remember in the future and gather resources if I run into this again.

**Pull request merged**
