### PR TITLE
Change syscall to os in terminal check for Windows compatibility

### PR DESCRIPTION
**Pull request by urbanyeti**
This is a fix for: https://github.com/segmentio/golines/issues/54
I believe this is the preferred approach to ensure cross-platform compatibility. Things are working for me now in Windows but I don't have a way of verifying things in another OS.

### CODE REVIEW

**Comment by telemachus** [comment]
For what it's worth, the current code works for me on macOS. I'll check with Debian later today.

Where is `os` recommended for portability?

**Comment by telemachus** [comment]
@yolken-segment Whichever way this goes, would it make sense to set up a GitHub action to test PRs against multiple operating systems? If so, I'd be up to look into that.

**Comment by urbanyeti** [comment]
@telemachus 

It’s not totally cexplicit, but looking around the official go documentation, that was my takeaway. The docs describe the ‘os’ package as being built with platform-independence in mind: https://pkg.go.dev/os

And then in the syscall package docs (https://pkg.go.dev/syscall) there’s a note saying that it’s deprecated and to use the platform specific ‘sys’ calls instead. And then if you look at windows/sys (https://pkg.go.dev/golang.org/x/sys/windows) it directly says that it’s better to use more portable interfaces like ‘os’ if you can.

**Comment by telemachus** [comment]
@urbanyeti Thanks for the links. I should have read the `syscall` documentation more carefully.

**Comment by yolken** [comment]
Thanks for the fix!

**Comment by yolken** [comment]
> @yolken-segment Whichever way this goes, would it make sense to set up a GitHub action to test PRs against multiple operating systems? If so, I'd be up to look into that.

@telemachus yes, it would be great to switch the CI to GitHub Actions and also add testing for multiple platforms! If you want to dig into that, that would be great.

**Comment by telemachus** [comment]
@yolken I'm happy to help, but I have a (maybe fuzzy) question. Do you think we should consider changing the behavior of the tool on Windows, or do you think we should just adjust the tests to account for the possibility of Windows-style line-endings (even though the tool still emits only `\n`)?

I have [a branch with GitHub actions working and the tests passing](https://github.com/telemachus/golines/tree/github-actions), but to get there initially, I simply punted on the tests. The two times that golden files are read from the repo, I ran `bytes.Replace` on the contents before running the tests. (Example: https://github.com/telemachus/golines/blob/d4076b3b593f88fd0d36863a60890e88c5b5d474/shortener_test.go#L69-L70.) This works, but feels like a hack. On the other hand, I wasn't sure whether it made sense for golines to change its line endings on Windows. Let me know if you have thoughts about how to move forward.

**Comment by yolken** [comment]
I'm really curious about where the `\r\n`s are being generated in the Windows case. From what I understand, go should not be using anything other than a `\n` for newlines when generating formatted output (see, for instance, https://github.com/golang/go/issues/28822). Maybe it's happening in the process of getting the output from `gofmt` or `goimports`?

In any case, I think it's ok to do some substitution on the test side if needed to get things passing. One small improvement- maybe you can update the test to only do the `bytes.Replace` if the `GOOS` is Windows (via something like https://golangbyexample.com/detect-os-golang/)? That way, we're keeping the restricting the scope of the hackiness here.

**Comment by telemachus** [comment]
> I'm really curious about where the `\r\n`s are being generated in the Windows case. From what I understand, go should not be using anything other than a `\n` for newlines when generating formatted output (see, for instance, [golang/go#28822](https://github.com/golang/go/issues/28822)). Maybe it's happening in the process of getting the output from `gofmt` or `goimports`?

I may be wrong, but I think the issue comes from [reading files in Windows](https://github.com/telemachus/golines/blob/github-actions/shortener_test.go#L61) rather than anything go (or go tools like `gofmt` or `goimports`) emits. That is, when go reads a file into an slice of bytes on Windows, the lines seem to be delimited by `\r\n` rather than `\n`. I was assuming that that was out of go's hands, so to speak. 

> In any case, I think it's ok to do some substitution on the test side if needed to get things passing. One small improvement for your proposed change- maybe you can update the test to only do the `bytes.Replace` if the `GOOS` is Windows (via something like https://golangbyexample.com/detect-os-golang/)? That way, we're restricting the scope of the hackiness here.

Yup, I'm happy to check for the OS before calling `bytes.Replace`. I'll update to master and see if I can test against 1.16, 1.17, and 1.18. (I'm not sure whether GitHub actions already supports 1.18, but I'll see.)

**Pull request merged**
